### ISSUE TITLE
Improve/expand FRSL configuration

### ISSUE THREAD

**Issue by tbembersimeao** [ctsit/form_render_skip_logic#11]
Currently, FRSL configuration form is limited:
- Only one control field
- Only one operator (_OR_) for multiple conditions over the same instrument

The ideal solution for this is hijacking REDCap's branching logic form, which would be powerful and user friendly. But since this approach would take a considerable amount of time to implement, I would like to brainstorm middle ground solutions for this.

We could start, for instance, by hijacking the "Advanced Branching Logic Syntax" only - which is a simple text area field - alongside with a popup helper. Later on we could build on top of it.

@pbchase @tlstoffs any thoughts?

**Comment by tlstoffs** [comment]
- Only one operator (OR) for multiple conditions over the same instrument – I’m not sure what you mean by this ☹ It looks like you can assign a form to show up for multiple conditions (Control field). I just did this in the FRSL project (PID 4051), where I was able to assign the ‘Butterfly Data’ form to both Butterflies and Parrots.  However, I’m not sure that’s what you are referring to...

- Only one control field – having more than one would be nice/useful. I can definitely see users needing more than one control field.

**Comment by tbembersimeao** [comment]
@tlstoffs yes, that explanation is confusing. Rephrasing:

For the configuration example below, `prescription_form` shows up if control value is 1 _or_ 2. If we decide to allow multiple control fields, we will need to support statements like <condition 1> _and_ <condition 2> on the interface somehow.

![screen shot 2018-04-05 at 1 28 08 pm](https://user-images.githubusercontent.com/29384017/38381866-272172d8-38d6-11e8-8fb0-2dec1d106562.png)

**Comment by pbchase** [comment]
The "one control field" limitation has been fixed by PR #19.

**Comment by tbembersimeao** [comment]
Another interesting feature that @pbchase and I discussed a few days ago is having a grade of checkboxes (instruments x events) in which we can pick individual forms to be displayed.

Something like:
```
                      Event 1 Event 2 Event 3
Instrument 1      [ ]         [x]         [ ]
Instrument 2      [x]         [ ]         [ ]
Instrument 3      [ ]         [ ]         [x]
```

**Comment by pbchase** [comment]
All of the desires discussed in this issue can be addressed in the current release of FRSL, version 3.3.3. To get a multi-valued control field used the Advanced Control field feature.
