### ISSUE TITLE
Branching logic behavior prior to control field save

### ISSUE THREAD

**Issue by tbembersimeao** [ctsit/form_render_skip_logic#14]
The current branching logic behavior is:
- Before a record is saved for the first time, all forms are visible and accessible
- Once a record is saved, branching logic starts to work
  - It starts to work even if control field's form is not saved yet. In this case, control field is considered empty (no matter the existence of a `@DEFAULT` action tag) so all forms depending on the control field get hidden

For consistency, we need to create the abilities of:
- Enable branching logic for non saved records, so forms visibility can be set since the very first beginning
- Use control field's `@DEFAULT` action tag as the default control value

**Comment by pbchase** [comment]
fixed by PR #15
