### ISSUE TITLE
Unexplained Errors

### ISSUE THREAD

**Issue by madisonalbright** [ctsit/form_render_skip_logic#17]
Hello,
I keep getting odd error emails although it seems to be working fine from the front end:

The 'form_render_skip_logic' module was automatically disabled because of the following error: Error Message: File: Line:   

Any ideas of where to go from here?

**Comment by pbchase** [comment]
@madisonalbright, we think we have addressed these errors. Today I submitted FRSL 3.3.3 to Vanderbilt's REDCap Repo.  Please upgrade at your next convenience and let us know if the problems recur.
