### ISSUE TITLE
Review frsl_data_collection_instruments hook for issues with REDCap 7.6.0

### ISSUE THREAD

**Issue by pbchase** [ctsit/form_render_skip_logic#2]
New save option in REDCap 7.6.0 might create problems for the frsl_data_collection_instruments hook.  Please test this hook in RC 7.6.0 to see if the new save options create problems.

**Comment by rajputd** [comment]
The new "Save & Exit Record" button and "Save & Go To Next Record" buttons in the Data Entry Forms do not cause any problems.

**Comment by rajputd** [comment]
The new "Save & Go To Next Record" button and "Save & Exit Record" button do not cause any issues directly. However they do change the layout of the menu when they are clicked (it is organized by most recent). This highlights that we created an extra "Save & Stay" button on that menu. 

![image](https://user-images.githubusercontent.com/16458008/28938728-f10c5dfa-785c-11e7-860d-281c4c4c36b6.png)

**Comment by pbchase** [comment]
I'm glad to hear there was no issue in the functionality, but glad you made this improvement. The old functionality was a little confusing. Fixed by PR #3
