### ISSUE TITLE
Additional support to control event level logic?

### ISSUE THREAD

**Issue by si-wehi** [ctsit/form_render_skip_logic#22]
Hi,

This has been a great tool for us and I was wondering if it was possible to add support to control/select the event in which a form is skipped.

Many thanks to your team!

**Comment by pbchase** [comment]
That exists in FRSL 3.0.0, but we made a breaking change in the configuration.  Take a look at the bottom of the README and let me know what you think: https://github.com/ctsit/form_render_skip_logic  

We released this yesterday and I have been meaning to get people's input on the forum. I think what we did was kind of evil, but we are working under a deadline and needed to get the new release out.  I don't want to publish it to the REDCap Repo until we talk about the breaking change and what it means for the upgrade path.  

I think we might need to declare FRSL 3 to be a completely different module so FRSL 2 and FRSL 3 can coexist in the same redcap instance.  I think this would be a much easier migration path. Changing one project at a time is much better than breaking every project's FRSL config at once. 

Lastly, issue issue #23 needs to be fixed before you use FRSL 3. 3.0.1 is coming very soon.

**Comment by pbchase** [comment]
@tbembersimeao, what do you think of my proposal to fork our own FRSL code and declare a new module with a new name? Any ideas for a new name?

**Comment by si-wehi** [comment]
Thanks @pbchase. Interesting idea to fork into a separate module, I wonder if there could be a function to copy all rules from the original once both are installed then you could discontinue the first version? 

Read me looks great, what options open up when you click the event check box, is it possible to select multiple events? 

Thanks!
Si

**Comment by pbchase** [comment]
I was chatting with the developer about an upgrade path for the configuration. He says there is a way we can probably do it. The module enable/upgrade event is hookable. That means we could run some software at the upgrade event. So maybe we _can_ provide an upgrade path. We are _not_ writing that right now though.  We are still make revisions under deadline.  

As to the event interface, yes, you choose multiple events.

**Comment by si-wehi** [comment]
That sounds great, thanks for the update! Looking forward to this being available on the EM repo.

**Comment by pbchase** [comment]
@si-wehi, Form Render Skip Logic 3.x is now ready for general use. FRSL is now in production on all of our REDCap hosts and I have submitted it the REDCap Repo. The critical component for each of those milestones was the 2.x-to-3.x migration code. It took us a few iterations, but that is now done. 

The blessed release is [3.3.3](https://github.com/ctsit/form_render_skip_logic/releases/tag/3.3.3)

**Comment by si-wehi** [comment]
@pbchase can't wait to try it out, just need to upgrade REDCap! Thanks!
