### ISSUE TITLE
Documentation needs a discussion of survey support

### ISSUE THREAD

**Issue by pbchase** [ctsit/form_render_skip_logic#36]
While FRSL has some survey support, the documentation does not mention it. At the very least we need to say something like this

> FRSL works with the _Auto-continue to next survey_ option of _Survey Termination Options_. It has not been well tested with Survey Queues.

**Comment by pbchase** [comment]
With respect to survey queues, Scott Robertson reported on 2018-08-18 in the REDCap Community:

> ...as long as you skip the survey in both places, the queue and FRSL, it works as expected

**Comment by ChemiKyle** [comment]
Addressed by PR #63
