### ISSUE TITLE
Bug in connection with DAGs

### ISSUE THREAD

**Issue by mschulze0** [ctsit/form_render_skip_logic#39]
Hi,

there seems to be a bug with this module version 3.3.3 and REDCap 8.8.1 when using DAGs. It only happens for DAGs that don't have any records in them. The bug disappears as soon as there's at least one record in that DAG.
What happens is, when you create a new record in an empty DAG then all forms appear as enabled even though some shouldn't be according to FRSL rules. I say appear as enabled because when you actually click on any form nothing happens and you just stay on the page for the new record instead of going to the form.

Thanks for you help! It's a great module otherwise!

**Comment by pbchase** [comment]
@mschulze0, we need to be able to reproduce this to fix it. Could you share the rules you are using? It sounds like you'd be using the advanced control mode so I'd need to see the value in the Equation/Piping field. A screenshot of FRSL module configuration page would be very helpful.

**Comment by mschulze0** [comment]
@pbchase Hi! My rules are rather complicated and I have a lot of them. Maybe I should create a minimal example first, but don't have the time right now. So you're saying that this bug is not occurring just by turning on DAGs? It has something to do with the specific rules I'm using?

**Comment by pbchase** [comment]
@mschulze0, thanks again for the bug report. I wanted to let you know we are now seeing this in one of our systems. Everything matches the patterns you described. We are finding the bug hard to replicate in a development environment, but at least we can now see it and have a better chance of understanding it. 

Have you acquired more details since February?

**Comment by mschulze0** [comment]
Hi,

no I didn’t investigate further. I simply worked around the issue by creating a dummy record for each DAG which I deleted once the first real record for a DAG has been created.

**Comment by pbchase** [comment]
@mschulze0, we can now recreate this bug in our development environments. The last piece is to configure FRSL to `Prevent hiding of filled forms`. Can you confirm that you are also using this switch?

**Comment by mschulze0** [comment]
@pbchase yes i'm using that!
