### ISSUE TITLE
Repeating Instruments Display Bug

### ISSUE THREAD

**Issue by nmunro42** [ctsit/form_render_skip_logic#40]
Using FRSL v3.3.3 on REDCap v8.9.1
A repeating instrument that should be hidden is showing as accessible in both the Record Status Dashboard and Record Home Page. 
If an attempt is made to access an instance the user is returned to the Record Home Page, regardless of which page the user was on when attempting to access the instance.
This is a repeating instrument in an event set to Repeating Instruments where most other instruments are not repeating.
The user cannot access the instances entered for the instrument but the display is showing the instrument as accessible.

Happy to provide further info is required.

<img width="649" alt="frsl_bug_01" src="https://user-images.githubusercontent.com/47514766/52546989-ca039700-2e13-11e9-9190-c09920dcdd3d.png">
<img width="75" alt="frsl_bug_02" src="https://user-images.githubusercontent.com/47514766/52546990-ca9c2d80-2e13-11e9-8e5f-552738cc4541.png">

**Comment by aanunez** [comment]
It looks like the js is just looking at the element's href, which in the case of a form that already has one recorded response is "javascript:;". One solution would be to add something like...

```
if (this.href == "javascript:;") {
    var params = this.getAttribute('onclick').split(',').map(function(e){return e.trim();});
    params = {id: params[1][1], event_id: params[2], page: params[3].substr(1,params[3].length-4)}
}
else {
```

in `frsl.js` at line 21 to pick apart the onlclick call. My end-users also have reported this issue.
