### ISSUE TITLE
loadFRSL does not generate nextStepPath setting with instance query parameter for data entry forms 

### ISSUE THREAD

**Issue by anthonycor** [ctsit/form_render_skip_logic#41]
I have a longitudinal study in which I've enabled "Repeat Entire Event (repeat all instruments together)" for one of the events which contains more than one data entry form, thus all data entry forms will have an instance query parameter (if it is not present redcap will assume the first instance) when you enter the form from the record status dashboard. However, it looks like the FRSL is not taking this instance query parameter into account when it calculates the nextStepPath, so after you click "Save & Go to Next Form" on the first form for the repeat event it doesn't keep the same instance query parameter, thus it always loads the first instance of the next form when really you want to edit that next form for the instance you were just on for the previous form.

#### REPO Steps:
1. study configured with at least two events and at least two data entry forms/instruments are mapped to the second event.
2. Configure the second event to be "Repeat Entire Event (repeat all instruments together)" in the "Enable optional modules and customizations" section of the project setup.
3. Complete both data entry forms for the first instance for a record id.
4. On a record dashboard for the same record id used in step # 3, click "Add new" to add the second instance of the repeatable event.
5. Complete the first form for the second instance (Note on this page the instance=2 query parameter). When you press "Save & Go to Next Form" to start the second for this instance query parameter is not there and thus REDCap loads the first instance of the "next form" that you created in step # 3, instead of taking to the next form for the same instance you were on for the previous form.

NOTE: I do not have any FRSL configuration set for this REDCap project.

REDCap v 8.10.1
FRSL v 3.3.3

**Comment by anthonycor** [comment]
I should have also noted that I do not have any FRSL configuration set for this REDCap project.

**Comment by pbchase** [comment]
@anthonycor, what does you mean when you say "NOTE: I do not have any FRSL configuration set for this REDCap project."? Are you saying FRSL interferes with normal event display merely be being enabled on a project?

**Comment by anthonycor** [comment]
Yes, FRSL is not configured, but enabled on this project. And when it is
enabled the “Save & Next Form” button will always load the first instance
of a repeating form because the nextStepPath is not including the instance
query parameter.

**Comment by pbchase** [comment]
addressed by PR #62
