### ISSUE TITLE
FRSL slows down the display of the record status dashboard

### ISSUE THREAD

**Issue by pbchase** [ctsit/form_render_skip_logic#49]
FRSL slows down the display of the record status dashboard. The script it slows down is `DataEntry/record_status_dashboard.php` Reducing the number of records displayed diminishes the problem, but we have production projects that take 13 seconds to display 10 subjects. 

Could you review the performance on this page and look for ways to speed it up?

**Comment by ChemiKyle** [comment]
The module processes logic for _all_ records, not just the ones shown, the slowdown for page delivery should be uniform across the number chosen to display (a few experiments has shown this is not true, but the difference from 10 records to 50 records is a few seconds). I think I will make a separate PR from the JavaScript optimizations to address this.

**Comment by ChemiKyle** [comment]
Addressed by PR #53
