### ISSUE TITLE
FSRL for multiple conditions

### ISSUE THREAD

**Issue by smruti272mokal** [ctsit/form_render_skip_logic#52]
Hi!

Can anyone please tell how can i skip forms using multiple control fields in FRSL?
It is kind urgent for a project submission.

Thank you.

**Comment by tlstoffs** [comment]
@smruti272mokal 
[Form Render Skip Logic External Module for Consortium.docx](https://github.com/ctsit/form_render_skip_logic/files/3462113/Form.Render.Skip.Logic.External.Module.for.Consortium.docx)

**Comment by tlstoffs** [comment]
@smruti272mokal , this guide should help:

[Form Render Skip Logic External Module for Consortium.docx](https://github.com/ctsit/form_render_skip_logic/files/3462114/Form.Render.Skip.Logic.External.Module.for.Consortium.docx)

**Comment by smruti272mokal** [comment]
> @smruti272mokal
> [Form Render Skip Logic External Module for Consortium.docx](https://github.com/ctsit/form_render_skip_logic/files/3462113/Form.Render.Skip.Logic.External.Module.for.Consortium.docx)

Thanks. In that case i guess i will have to look around some logics. I hope this module will support multiple conditions on overlapping forms in the future.

**Comment by pbchase** [comment]
@smruti272mokal, we have no intention of supporting control fields with overlapping sets of forms.
