### ISSUE TITLE
User being directed to unauthorized page

### ISSUE THREAD

**Issue by dowdf** [ctsit/form_render_skip_logic#57]
I am on REDCap 9.1.1 and using version 3.3.7
In an event on a longitudinal project in production mode, if a user is on a form where the module has hidden the rest of the forms in the event, but there is another form in the event that is hidden due to user rights, but not hidden by the module, REDCap displays Save and go to next form. That takes the user to the form that should be hidden because of user rights, and the user gets an unauthorized message for that page.  This doesn't happen in development mode.

**Comment by pbchase** [comment]
@dowdf, can you help us recreate the problem you are experiencing? So screenshots of what you are seeing might be helpful. A project XML and a screenshot of the FRSL module configuration could also be helpful.

**Comment by dowdf** [comment]
I stripped down the project and exported it.  I’ve attached screen shots of the module configuration, the user rights page for the role, and the data entry/error.  I found out that the error happens for both development and production modes.  Our site uses shibboleth authentication.  Please let me know if there is anything else that would help you reproduce the problem.

**Comment by pbchase** [comment]
@dowdf, Thanks for the additional data, but your screenshots are not attached. Could you upload them directly at https://github.com/ctsit/form_render_skip_logic/issues/57 ?

Also, I can't help but think that your error reminds me of complaints people have our Linear Data Entry Workflow module. Are you using that as well?

**Comment by dowdf** [comment]
Here are screen shots and the XML as a zip.  I am not using the Linear Data Entry Workflow module.


[KPMPParticipantManag_2019-10-11_2115.REDCap.zip](https://github.com/ctsit/form_render_skip_logic/files/3732138/KPMPParticipantManag_2019-10-11_2115.REDCap.zip)

![2 entry grid](https://user-images.githubusercontent.com/43256676/66882043-c9606900-ef7d-11e9-9ad5-5c0721c627f8.png)
![5 module config](https://user-images.githubusercontent.com/43256676/66882044-c9606900-ef7d-11e9-85f0-298e1dfccb56.png)
![4 Error form](https://user-images.githubusercontent.com/43256676/66882045-c9606900-ef7d-11e9-89f3-cb01ee4bae97.png)
![3 first form](https://user-images.githubusercontent.com/43256676/66882046-c9606900-ef7d-11e9-9f64-a39f1e67d2c3.png)
![1 User rights](https://user-images.githubusercontent.com/43256676/66882047-c9606900-ef7d-11e9-89c2-0184a3dd8743.png)

**Comment by NikNakk** [comment]
I'm having exactly the same issue. It would be helpful if this could be fixed. Great module by the way.

**Comment by NikNakk** [comment]
I've made a proposed fix for this issue at https://github.com/NikNakk/form_render_skip_logic/tree/fix_user_rights . Note that at present it does not respect the 'View project as user' option for admins, but should work ok in normal use. I've also not yet done extensive testing. I'd be happy to make a pull request if helpful but thought I'd add it to the issue discussion first.

**Comment by NikNakk** [comment]
I've now got it to handle the 'View project as user' option too.
