### ISSUE TITLE
Can't Specify Control Setting

### ISSUE THREAD

**Issue by ajperdew** [ctsit/form_render_skip_logic#77]
When configuring the module, around control field 11, both the default and advanced control settings  appear regardless of which option is chosen. I can't get either to work

![image004](https://user-images.githubusercontent.com/52385031/81121144-08471380-8efc-11ea-9f0d-b551b1a9e43b.jpg)

**Comment by ajperdew** [comment]
I'm running REDCap 9.5.18 and have tried FRSL v3.3.10 and v3.3.11

**Comment by mschulze0** [comment]
Hi,

this issue still exists and also happened to me once I added control field 11. At that point it also breaks the display of all previous control fields (but functionality remains).

**Comment by ChemiKyle** [comment]
Addressed by #87

**Comment by mschulze0** [comment]
@ChemiKyle any hint when the update will be released? :)

**Comment by ChemiKyle** [comment]
Soon! I definitely want to release this week.  
I'm looking for low hanging fruit to bring in to the same release, but this has been bothering us for _years_ so it will get its own if needed.
