### ISSUE TITLE
If a record's primary key (record_id) has a space in it, FRSL will not load on its Record Home Page

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/form_render_skip_logic#81]
The issue occurs here:

https://github.com/ctsit/form_render_skip_logic/blob/bc7413b0976e6358d1ac77018eae2b1fa0428936/js/frsl.js#L29

`params.id` is HTML escaped, but the key in `formRenderSkipLogic.formsAccess` is not! `REDCap::escapeHtml()` does not translate a space (` `) to a plus (`+`)!

**Comment by ChemiKyle** [comment]
@mbentz-uf You may want to take a look at this issue.

**Comment by mbentz-uf** [comment]
Addressed by #88
