### ISSUE TITLE
REDCap External Module Error - form_render_skip_logic

### ISSUE THREAD

**Issue by tertek** [ctsit/form_render_skip_logic#85]
We have a project with 60k records, 2k fields and 16 surveys. The type of the project is with repeating events. 
We are using Form Render Skip Logic - v3.3.11 in this project with two control fields. **Some of the target forms are with repeating events**. The configuration is valid and the module is working fine except when we would like to access the "Record Status Dashboard":

```
The 'hook_every_page_top' hook did not complete for the 'form_render_skip_logic' module because of the following error. Stack traces are unfortunately not available for this type of error:

Error Message: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 12288 bytes)
File: /opt/rh/httpd24/root/var/www/html/redcap/modules/form_render_skip_logic_v3.3.11/ExternalModule.php
Line: 300


URL: https://****************/redcap/redcap_v10.6.4/DataEntry/record_status_dashboard.php?pid=43
Server: ****************
User: *********
Module Name: Form Render Skip Logic (form_render_skip_logic)
Module Author(s): pbc@ufl.edu, tls@ufl.edu, kyle.chesney@ufl.edu
Run Time: 392 seconds

```

As you can read out from the error message, we are not able to load the "Record Status Dashboard" because the module "Form Render Skip Logic" is exhausting the memory limit. The problem seems to occur in the code around line 300, while "Building forms access matrix." A possible problem source could be time complexity: reaches here cubic time (n^3).

## Possible fixes:
- Increase the memory limit:
As the typical workaround this would make things only more problematic, since our memory limit is already high enough
- Enable support for repeating events :
As you have mentioned in your docs, repeating instruments "are not fully supported" and "[p]roper repeating events support is planned for a future release." Since I am not into the code too much I only have this suggestion:
-- optimize code while "Building forms access matrix" => reduce time complexity
-- fix other problems in relation with "repeating events"

Can someone who knows the code comment on this?

**Comment by ChemiKyle** [comment]
Hi @tertek,

Are you displaying all records per page? An optimization was introduced in version 3.3.10 to get better performance on Record Status Dashboard, but requires you limit the records per page to limit the size of the input space.

See issue #49 and its linked PR for technical details.

**Comment by tertek** [comment]
Hi @ChemiKyle ,
Unfortunately I cannot tell the value for "record per page" since we cannot access the page. But I guess that requesting with URL parameters should have the same effect which did not work for us either:

    ../DataEntry/record_status_dashboard.php?pid=43&num_per_page=10&pagenum=1

or

    ../DataEntry/record_status_dashboard.php?pid=43&num_per_page=1&pagenum=1
   
did not load and resulted in 504 Gateway Time-out.
